### ISSUE TITLE
1 minute of excel freeze when actions clicked.

### ISSUE THREAD

**Issue by Sam-D03** [didikunz/CasparCGAddIn#1]
Hey Didi,

Firstly, amazing work - this client really is an awesome idea! I'm playing around with it because I'd love to give it a use in my word, but every time I click anything - excel locks up for about a minute, and then caspar received the command and carries out the action.

During the minute of lock up, excel cannot be interacted with (but does NOT show 'not responding').

What version of excel should I be using with this? Do you have any idea why this delay is happening?

Thanks so much for any help :)

**Comment by didikunz** [comment]
Hi Sam,

I use Excel 2016. But I would guess, that some werid thing with your network config is doing the issue. Some firewall or anti virus, that keeps the commands from going through. Can you try with some other client, if that works without delay? 

Another idea: Have enabled the Auto-Update button? That makes a power query run before the template is updated. But that would only work, when there is a power query connected to the worksheet.

**Comment by didikunz** [comment]
I close this for inactivity, as I expect the problem to have vanished.
