### ISSUE TITLE
unload at end of clip

### ISSUE THREAD

**Issue by NafetsM** [didikunz/CasparCGAddIn#3]
Hi didikunz,
I'm using the AddIn for baseball live streaming. Via the list I'm playing clips and want them to fade or cut out at the end. Is there a simple way to do that? 
Best regards,
NafetsM

**Comment by didikunz** [comment]
Hi,
there is no such option in the AMCP protocol out of the box. As the PLAY command always freezes on the last frame. I usually use a separate output for the clips, so that the director can cut away, whenever he wants. What is your use case? for this? So that I know, if it would make sense to add something to the add-in.

**Comment by NafetsM** [comment]
Hi,
I'm using Caspar CG as an overlay in OBS and the clips should work like a stinger transition. Is it a possibility to autoplay an empty clip afterwards to clear the layer?

**Comment by didikunz** [comment]
Currently only by adding a separate line and writing a 1 into the "Autoplay" column. Then after the clip starts, you would load that line. Another option would be to build a template, that plays the clip and Loads the empty clip or by using a codec with alpha channel and adding a fade/cut to full transparent at the end of the clip.

**Comment by NafetsM** [comment]
OK, thanks. I'll try that.

**Comment by NafetsM** [comment]
What came to my mind yesterday evening is a simple "Stop" at the end of the clip. I just don't know if there is any feedback if the clip has already ended from CCG.

**Comment by didikunz** [comment]
As soon as I touch the add-in for the next time, I will add an auto-stop function to it. It does currently not monitor the status of Caspar, but I can add a LOADBG EMPTY after the play...

**Comment by didikunz** [comment]
Ok I added this. Find the installer and getting started manual on the main page. Add a column after "Show 1st Frame" like so:
![Grab1](https://user-images.githubusercontent.com/6048776/115062891-2595a780-9eeb-11eb-970a-99121e425950.PNG) 
If set to 1 it will do the trick. See the manual for further instructions

**Comment by NafetsM** [comment]
Thanks a lot. I will run a test tomorrow.

**Comment by NafetsM** [comment]
Works great! Again thank you very much.
