### ISSUE TITLE
Countdown-Timer?

### ISSUE THREAD

**Issue by Freeedooo** [didikunz/CasparCGAddIn#6]
Hey Didi,
will there be a Countdown-Timer in the AddIn soon? 

Sorry if this is the wrong place for that question. Didnt know where else to post.
Kind regards,
Freedooo

**Comment by didikunz** [comment]
Currently the timer can only count upwards. But that should not be a big issue to implement. What would you use it for? What would it needs to do? Stop on reaching zero? etc.

**Comment by Freeedooo** [comment]
I would use it as a countdown to the next game, match, race etc.

Main features would be:
- Start from specified time
- Stop on zero (as you already mentioned)
- Maybe pause/resume
- Maybe add or subtract time while counting

This would be an awesome feature to have!

**Comment by didikunz** [comment]
Aha, I see. But a countdown to the next game is something, that can be done inside a template (that is how I do these): You send a time value to the template, the time is the moment in time, when the next race starts (StartTime). Then inside the template have a timer ticking every second and calculate the difference of the current time and the StartTime and format this in (hours), minutes and seconds. Doing it that way makes it much easier to start such a timer, as you do not need to calculate the time offset before you start, but only send the StartTime, that you probably already know a week before the event and can prepare that as if you prepare lower thirds and the like.

**Comment by Freeedooo** [comment]
You might be right, but I do not know the exact time when a second match will start. I only know that the next match is in 5 mins or something. I don't think this is possible via the way you wrote there - or is it?

**Comment by didikunz** [comment]
You are right, for a fixed amount of time it makes sense to do it with a countdown. I am currently building the count down...

**Comment by didikunz** [comment]
I did a setup [here](https://www.dropbox.com/s/ejz4hv6kibdr4t7/CasparCGAddInSetup_TEST.zip?dl=0) but I am not too sure, if it works correctly. In the timers setup dialog you can set it to count down and also need to set a start offset...

**Comment by Freeedooo** [comment]
Hey Didi,
THANK YOU FOR THIS AWESOME WORK! The AddIn and the Counter are working perfectly fine. PLEASE let me know, if there is any way to thank you (via a little donation for example). 

With kind regards,
Freeedooo
